version: '3.9'
services:
  web:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - ${APP_PORT}:9000
    networks:
      - default
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: docker_sonarqube_network
    driver: bridge

volumes:
  data:
    name: docker_sonarqube_data
    driver: local
