version: '3.9'
services:
  web:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 29000:9000
      - 29092:9092
    networks:
      - default
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
